### ISSUE TITLE
[SRS subsection] - architectural requirements

### ISSUE THREAD

**Issue by Mathenda** [COS301-SE-2024/Events-System#11]
# Working-On

## Description

create architectural requirements based on functional requirements given
add quality requirements
architectural patterns
design patterns
constraints

## Additional Information

[Any additional details or context that might be helpful.]

**Comment by Mathenda** [comment]
Specify and quantify each of the system’s quality requirements. Examples of quality
requirements include performance, reliability, scalability, security maintainability, and
usability

**Comment by KezlynGovender** [comment]
Just the architectural patterns is left to do
