### ISSUE TITLE
SRS subsection

### ISSUE THREAD

**Issue by Mathenda** [COS301-SE-2024/Events-System#8]
# Working-On

## Description

SRS does not need to be finalized, or complete, Agile = constant iterations
SRS Should contain
Introduction
User stories
Functional requirements
service contracts
class diagram
architectural requirements
-quality requirements
-architectural patterns
-design patterns
-contraints
-technology requirements

## Additional Information

[Any additional details or context that might be helpful.]

**Comment by KezlynGovender** [comment]
what does subsection refer to
